
// [NEW] Mock Data for Cross-City Search (YanJiao/Hebei)
{
    id: 'yj01',
        title: '燕郊天洋城 精装两居室',
            type: PropertyType.RENT,
                category: '住宅',
                    status: PropertyStatus.AVAILABLE,
                        price: 2200,
                            area: 88,
                                layout: '2室1厅',
                                    location: '河北廊坊',
                                        address: '燕郊开发区天洋城',
                                            tags: ['跨城通勤', '近北京', '物美价廉', '小区环境好'],
                                                imageUrl: 'https://picsum.photos/400/300?random=118',
                                                    description: '位于燕郊核心区，楼下有影院超市。适合在北京国贸上班的通勤族，有直达公交，车程约50分钟。',
                                                        commuteInfo: '距离国贸CBD 30公里，公交快线直达',
                                                            coordinates: { lat: 39.9600, lng: 116.8000 },
    leaseTerms: ['年租'],
        landlordType: LandlordType.INDIVIDUAL
},
{
    id: 'yj02',
        title: '大厂孔雀城 联排别墅',
            type: PropertyType.RENT,
                category: '别墅',
                    status: PropertyStatus.AVAILABLE,
                        price: 6000,
                            area: 200,
                                layout: '4室2厅',
                                    location: '河北廊坊',
                                        address: '大厂潮白河孔雀城',
                                            tags: ['度假', '养老', '环境优美', '自带花园'],
                                                imageUrl: 'https://picsum.photos/400/300?random=119',
                                                    description: '潮白河畔，环境优美，空气清新。适合周末度假或有车一族。开车至通州副中心仅需40分钟。',
                                                        commuteInfo: '距离通州潞城地铁站 15公里',
                                                            coordinates: { lat: 39.8800, lng: 116.7500 },
    leaseTerms: ['年租', '长租'],
        landlordType: LandlordType.INDIVIDUAL
},
